### ISSUE TITLE
Not working with GH master

### ISSUE THREAD

**Issue by devemux86** [karussell/graphhopper-osm-id-mapping#1]
After the changes in this GH [commit](https://github.com/graphhopper/graphhopper/commit/66e70685fb9c461554ccc1ad741a457dd65bba0f) the example does not work properly anymore.

This is because the overridden `load` does not get called now. `importOrLoad` calls directly the `initializeStorage` which is `private`, so we have not access to it. :disappointed:

**Comment by karussell** [comment]
Thanks - related to: https://github.com/graphhopper/graphhopper/pull/700

Will think about a 'post-load' hook and should be fixed before 0.7 release

**Comment by karussell** [comment]
This is fixed in the master of GH - thanks again for reporting!

**Comment by devemux86** [comment]
Thanks for the fix!
