### ISSUE TITLE
Cann't load edge_mapping data 

### ISSUE THREAD

**Issue by solderain** [karussell/graphhopper-osm-id-mapping#3]
Try to run the demostration, but get below error   info : 
![image](https://user-images.githubusercontent.com/4144738/32710023-a05e44ac-c7fa-11e7-974b-95255f006360.png)
I noticed there is no edge_mapping file , only file named "edges" as below :
![image](https://user-images.githubusercontent.com/4144738/32710041-cf234760-c7fa-11e7-89a3-a435f4b81b61.png)
, try to change the file name to "edges" , but get the such error : 
![image](https://user-images.githubusercontent.com/4144738/32710075-17986796-c7fb-11e7-8bd9-6302f2938fee.png)
I have no idea about that ,  pls help what is problem ? @karussell

**Comment by solderain** [comment]
Resolved it

**Comment by karussell** [comment]
Please add how and also include the error message as text. Images are not really searchable

**Comment by YanzheZhangleon** [comment]
how did you resolved it, i have the same problem
